### ISSUE TITLE
小窗问题

### ISSUE THREAD

**Issue by ghr1025** [xiaoyaocz/AllLive#3]
1.小窗横向拉伸只能拉伸一点，不能随意拉长
2.能否添加直播窗口固定在最顶层的按钮

**Comment by xiaoyaocz** [comment]
UWP窗口置顶只能通过小窗API实现，窗口大小无法自定义。

**Comment by boxjohn** [comment]
> 1.小窗横向拉伸只能拉伸一点，不能随意拉长
> 2.能否添加直播窗口固定在最顶层的按钮

老哥你哪来的安装包阿，我怎么找不到

**Comment by ghr1025** [comment]
> > 1.小窗横向拉伸只能拉伸一点，不能随意拉长
> > 2.能否添加直播窗口固定在最顶层的按钮
> 
> 老哥你哪来的安装包阿，我怎么找不到

自己下个vc2019编译运行

**Comment by ZiQiLin2** [comment]
能否提供下安装包，感谢
