### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by ghr1025** [xiaoyaocz/AllLive#4]
首先win11风格很好看
但是编译release版本时会报错，只有debug版本可以出包，望解答
![IMG_20210928_154233_119](https://user-images.githubusercontent.com/72141677/135044667-b8a2075e-886f-4697-b62a-d633d02789c2.jpg)

**Comment by xiaoyaocz** [comment]
你好，可以参考下AllLive.UWP项目下的README
https://github.com/xiaoyaocz/AllLive/blob/master/AllLive.UWP/README.md
